---
- name: prometheus - check data source in grafana
  uri:
    url: "http://{{ prometheus_grafana_host }}:{{ prometheus_grafana_port }}/api/datasources/name/prometheus-{{ inventory_hostname_short }}"
    user: "{{ prometheus_grafana_username }}"
    password: "{{ prometheus_grafana_password }}"
    force_basic_auth: yes
  register: prometheus_ds
  failed_when: false
  changed_when: false

- name: prometheus - create data source in grafana
  uri:
    url: "http://{{ prometheus_grafana_host }}:{{ prometheus_grafana_port }}/api/datasources"
    method: POST
    user: "{{ prometheus_grafana_username }}"
    password: "{{ prometheus_grafana_password }}"
    body:
      name: "prometheus-{{ inventory_hostname_short }}"
      type: "prometheus"
      url: "http://{{ prometheus_host }}:{{ prometheus_port }}"
      access: "proxy"
    force_basic_auth: yes
    status_code: 200
    body_format: json
  when: prometheus_ds.status == 404
