---
- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ required_packages_prometheus }}"

- name: prometheus - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0755
  become: true
  with_items:
    - "{{ prometheus_docker_compose_directory }}"
    - "{{ prometheus_configuration_directory }}"

- name: prometheus - copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - src: prometheus.yml.j2
      dest: "{{ prometheus_configuration_directory }}/prometheus.yml"
  notify: Reload prometheus configuration

- name: prometheus - copy docker-compose.yml file
  template:
    src: docker-compose.yml.j2
    dest: "{{ prometheus_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640

- name: prometheus - run service
  docker_service:
    project_name: prometheus
    project_src: "{{ prometheus_docker_compose_directory }}"
    pull: yes
