---
- name: Install python2
  hosts: all
  gather_facts: no

  tasks:
  - name: Install python2
    raw: test -e /usr/bin/python || (test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal))
    register: result
    changed_when: result.rc != 0
    become: true

- name: Playbook for preparations
  hosts: all

  vars:
    docker_user: ubuntu

  roles:
    - osism.docker

- name: Playbook for role testing
  hosts: all
  connection: paramiko

  vars:
    operator_user: ubuntu
    prometheus_telegraf_group_name: all
    prometheus_configure_grafana_ds: false
    api_interface: enp0s3

  roles:
    - role: ../../ansible-prometheus
