---
- name: Reload alertmanager configuration
  uri:
    url: "{{ prometheus_alertmanager_protocol }}://{{ prometheus_alertmanager_host }}:{{ prometheus_alertmanager_port }}/-/reload"
    method: POST

- name: Reload prometheus configuration
  uri:
    url: "{{ prometheus_protocol }}://{{ prometheus_host }}:{{ prometheus_port }}/-/reload"
    method: POST

- name: Restart nginx service
  command: "docker-compose -f {{ prometheus_docker_compose_directory }}/docker-compose.yml restart nginx"
